name: Backend integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use the same Python version as your local environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements-dev.txt  # Install development dependencies like pytest, pre-commit, etc.

    - name: Run Unit Tests
      working-directory: backend
      run: |
        pytest tests_container/unit --maxfail=5 --disable-warnings

    - name: Run Integration Tests
      working-directory: backend
      run: |
        pytest tests_container/integration --maxfail=5 --disable-warnings

  # Job 2: Build Docker image and push to Docker Hub
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Image
      working-directory: backend  # Change directory to 'backend'
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/stock-view-backend:${{ github.sha }} -f Dockerfile .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/stock-view-backend:${{ github.sha }}

  # Job 3: Pull Docker image and run container
  pull-and-run:
    name: Run integration test on container
    runs-on: ubuntu-latest
    needs: build-and-push  # This job depends on build-and-push

    steps:
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stock-view-backend:${{ github.sha }}

    - name: Run Docker Container
      run: |
        docker run -d ${{ secrets.DOCKERHUB_USERNAME }}/stock-view-backend:${{ github.sha }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use the same Python version as your local environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements-dev.txt  # Install development dependencies like pytest, pre-commit, etc.

    - name: Run docker integration tests
      working-directory: backend
      run: |
        pytest tests_container/docker --maxfail=5 --disable-warnings
